services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: library_app

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    command: uv run python src/main.py


    networks:
      - library_network

  db:
    image: postgres:16

    container_name: library_db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - library_network

volumes:
  postgres_data:

networks:
  library_network:
    driver: bridge